version: '3.9'

services:
  db:
    container_name: postgres
    build: .
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d test"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
