version: '3.9'

services:

  db:
    container_name: postgres-server
    build: ./services/server/
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./services/server/.env.server
    ports:
      - "5435:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 5s

  client:
    image: jbergknoff/postgresql-client
    container_name: postgres-client
    restart: unless-stopped
    env_file:
      - ./services/client/.env.client
    expose:
      - 5432
    command: -h postgres-server
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
