CREATE ROLE root WITH LOGIN SUPERUSER PASSWORD 'superuserpassword';
CREATE USER admin WITH CREATEROLE CREATEDB PASSWORD 'supersecretpwd';

CREATE DATABASE zarplata;
ALTER DATABASE zarplata OWNER TO admin;
GRANT ALL PRIVILEGES ON DATABASE zarplata TO admin;