CREATE ROLE root WITH LOGIN SUPERUSER PASSWORD 'superuserpassword';
CREATE USER admin WITH CREATEROLE CREATEDB PASSWORD 'supersecretpwd';

CREATE ROLE employee WITH NOLOGIN;
CREATE ROLE accounting WITH NOLOGIN;
CREATE USER employee_vasiliy WITH INHERIT LOGIN IN ROLE employee PASSWORD '1234';
CREATE USER accounting_anna WITH INHERIT LOGIN IN ROLE accounting PASSWORD '1234';

CREATE DATABASE zarplata;
ALTER DATABASE zarplata OWNER TO admin;
GRANT ALL PRIVILEGES ON DATABASE zarplata TO admin;